//created on: 06.05.2016
package de.hdm.wim.events;

import de.hdm.wim.events.model.Token;
import de.hdm.wim.events.documentrepresentation.DocumentRepresentationRequester;
import de.hdm.wim.events.model.Project;

global java.util.List resultList;

declare Token
    @role( event )
    @timestamp( timestamp.getTime() ) //long
end

rule "A Token occured" dialect "mvel"
  when
      $t : Token() from entry-point SpeechTokenEventStream
  then
  	  resultList.add( "A Token occured");
      System.out.println( "A Token occured!"); 
      DocumentRepresentationRequester requester = new DocumentRepresentationRequester();
      Project project = requester.getProject("P0001");
      System.out.println( "requested project: " + project);
end

//rule "Example Rule"
 //   when
  //      $t : Token(keyword=="HighNet") from entry-point SpeechTokenEventStream
  //      $t.projects contains
  //  then
  //      DocumentRepresentationRequester d = new DocumentRepresentationRequester();
//end
